### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by trusktr** [dmvaldman/samsara#1]
Hi @dmvaldman,

would you like to join the community efforts over at github.com/infamous/motor? That is a community project where we wish to create a community-led alternative to Famous. We're currently in the state of writing prototypes and then after a while we'll take our ideas and decide on the route we want to take. The prototype that you have here could be a huge help. We want to garner the best ideas into the route that we choose to take. Others that have recently left Famous are excited to join, but are waiting for their non-compete contracts to expire.

These are the channels that we've been having discussions in:

http://gitter.im/infamous/famous-engine (we forked Famous Engine)
http://gitter.im/infamous/motor (but we are more excited to work on our own community-led solution instead)

Join us and share ideas with us! I've sent you an invitation to the infamous group (the name "infamous" and "motor" are subject to change, but it's what we're working with for the time being.)

**Comment by trusktr** [comment]
> Keep fighting the good fight. Good luck.

And, and thanks for the good words!

**Comment by dmvaldman** [comment]
This project began from version 3 of famous (now deprecated), but has diverged considerably from that point. There have been over 750 commits since then. I'm happy to discuss ideas, but this project has an identity of its own now and I would prefer to not associate it with its inception.
