### ISSUE TITLE
Carousel index dots update pretty slowly on Carousel Demo

### ISSUE THREAD

**Issue by lluia** [dmvaldman/samsara#17]
Usually index dots on Carousel updates at the same time you click on them or in one of the Carousel arrows. In the demo it takes a while until the active dots is highlighted when changing slide. I think fixing this will help make appear the library more stable.

**Comment by dmvaldman** [comment]
The logic of the app is set to update the dots at the end of the transition. But you can alter it to update at the beginning if you like!
