### ISSUE TITLE
Reference Docs Missing

### ISSUE THREAD

**Issue by roblav96** [dmvaldman/samsara#21]
This link to the reference docs is MIA :(
http://samsarajs.org/reference_docs

**Comment by dmvaldman** [comment]
http://samsarajs.org/reference_docs/index.html

Because I'm hosting things on Amazon's Cloudfront, I need to use actual file paths for some reason. I'd like to get around that somehow...

**Comment by roblav96** [comment]
Thank you!

**Comment by dmvaldman** [comment]
Ah! I found how to fix it. Ridiculous http://someguyontheinter.net/blog/serving-index-pages-from-a-non-root-location-via-cloudfront/

Now directories resolve

**Comment by roblav96** [comment]
Lol! I don't have too much experience with AWS but I've heard mixed reviews.

I ended up doing server colocation locally in Boston. Host all my own stuff on my own server hardware. Its great!
