### ISSUE TITLE
Broken rendering on Android Chrome

### ISSUE THREAD

**Issue by amannn** [dmvaldman/samsara#22]
First of all, really great stuff! From a first look at the API and the examples, this looks really interesting!

However, when I run the demos of your website on my mobile phone, the rendering seems to break quite heavily.

<img src="https://cloud.githubusercontent.com/assets/4038316/12898119/649b58be-ceab-11e5-84e5-f8f5c7bbee7b.png" width="400">

<img src="https://cloud.githubusercontent.com/assets/4038316/12898131/6da17498-ceab-11e5-817f-ae0a75d7df57.png" width="400">

These are just two examples – except from the logo, all the demos seem to break in some way or another.

I'm using Chrome on my Motorola Moto X 3rd Gen running Android 5.

But the phone also has some issues rendering box-shadows, as described [here](http://stackoverflow.com/questions/33376110/weird-box-shadow-bug-in-chrome-on-android) – I don't know if that is related somehow.

**Comment by dmvaldman** [comment]
I've tested the site on a Nexus 5 running android 5, but there is a lot of hardware inconsistency on phones. I don't have my Android devices on me at the moment, but will do some more testing on them soon. For now, do the demos work when you click the full screen button?

**Comment by amannn** [comment]
Actually yes, in full screen all the demos work pretty good.

**Comment by bardu** [comment]
I have tested the demos on Samsung S6 Edge with Android 5.1.1, Google Chrome and FF, iPhone 6, 5s, 4 with iOS 9.2.1, Google Chrome and Safari.

On all devices very fluid animation, great job David.

**Comment by dmvaldman** [comment]
Thanks for testing on your devices @bardu! I've just also tested on a 2012 Samsung Nexus 3 running Android 4.3 and everything rendered correctly (though the performance was noticeably worse).

I'm not sure what the problem could be @amannn. If anyone happens to have the same device (Moto X 3rd Gen), please test!

**Comment by amannn** [comment]
Oh I just noticed it was a Moto **G** 3rd Gen – sorry for the misinformation! The specific Android version is 5.1.1 by the way.

We can also close this in the meantime, as the full screen demos work and it appears to only affect that special phone.

**Comment by roblav96** [comment]
I've testing on:
- iphone 5s, 6, 6s, ipad 2, ipad 3
- HTC m8, m9, Nexus 7, 9, Galaxy s4, s5 (all on 5.x)
- Nexus 10 on 4.4.4
All work phenomenally.

**I have found my ios devices to perform almost twice as better.**
On my androids, I'm getting a lot of translucent bars:
![screen shot 2016-02-09 at 9 23 01 am](https://cloud.githubusercontent.com/assets/1457327/12918785/da2991a0-cf0e-11e5-9c32-f8d883f33e32.png)
I believe the white translucent bars indicate many things, (idle, unkown scripting, or GPU bottleneck) but it has been persistent on most of my android devices. The extra tall clear bars are idle times.

**Comment by dmvaldman** [comment]
Android has always lagged behind iOS in this respect. Their software isn't as efficient so their solution is to throw better hardware at the problem. It's only in the last 2-3 years that the hardware has been good enough to run web apps near 60fps.

Thanks for testing @roblav96! 

Closing as this seems to be a specific issue with the Moto G and not Samsara

**Comment by culyun** [comment]
The IOS / Android performance differential may be partially due to the Blink / Webkit fork.

There's an [analysis](http://browserg.nom.es/) of the fork one year on with the commentator noting...

> The WebKit project has been more focused on documents and improving existing pages with faster line layout and style selection

I've tried the demos on an iphone 5 running safari 7.  It's slick :-)
The same demos on a 6-month old android tablet are not as silky (but still great)

But the sad news to my mind is Windows mobile.  Microsoft has been doing some great work with Edge.  But on my Lumia 820 it still feels like ie, ie. slow and clunky.

@dmvaldman thanks for the great work and lucid documentation.  I'm fiddle-farting around with a Samsara + MithrilJS combo.

**Comment by dmvaldman** [comment]
Thanks! Would love to see the integration @culyun
