### ISSUE TITLE
Media Abilities

### ISSUE THREAD

**Issue by Acostan** [dmvaldman/samsara#23]
Hi,

Is there any support or plans to support embedding Video or Audio (players) as a node in the tree especially on iOS, so that we can build custom interfaces without being forced to play video using the default video player on iOS and other devices? Thanks in advance.

**Comment by dmvaldman** [comment]
Have you seen http://stackoverflow.com/questions/5054560/can-i-avoid-the-native-fullscreen-video-player-with-html5-on-iphone-or-android#5057297

You can use the attribute `webkit-playsinline` in an HTML5 video tag to let the video stay in the webpage (for a web app, not a website seen on Safari)

There's no plans to support this as a native Samsara component, but there's nothing that stops you or someone else from building such a view. You can create a `video` tag with a Samsara surface as follows

```
var videoSurface = new Surface({
    size : [width, height],
    tagName : 'video',
    attributes : {
        webkitPlaysinline : true,
        src : yourURL
    }
})
```

**Comment by Acostan** [comment]
That's great info! Thanks alot.
