### ISSUE TITLE
Reactive Data

### ISSUE THREAD

**Issue by Acostan** [dmvaldman/samsara#24]
If Content comes from a Handlebars template for example, and lets say that Handlebars template contains some reactive data (meteorjs), will that reactive data appear in the Surface without having to write code to re-render? Or will the data automatically stream the content from the handlebars template?

PS: Keep up the excellent work!!!

**Comment by dmvaldman** [comment]
This might be of help: http://stackoverflow.com/questions/28615327/running-a-function-after-a-meteor-template-is-updated?rq=1

There will need to be some hook established. Something eventually asks the template to re-render, and afterwards the `Surface` associated will have to call `setContent`.
