### ISSUE TITLE
Mounting to body removes all other classes

### ISSUE THREAD

**Issue by roblav96** [dmvaldman/samsara#26]
I have a cordova hook that appends the platform to the body tag in my index.html

When I mount samsara to the body, the classes are overwritten by 'samsara-context'

If I add the classes into the index.html manually, they don't get removed.

**Comment by dmvaldman** [comment]
I'm not sure what you mean by "appends the platform to the body tag". I thought maybe there was a bug where classes are overwritten, but as you say when you have manually preset classes, Samsara doesn't override them on `mount`. I'm not sure why you're getting this behavior.

**Comment by roblav96** [comment]
Ye that's my bad. I was trying some new techniques. lol
