### ISSUE TITLE
Option/Configure for PreventDefault on TouchInput and ScrollInput to prevent native scrolling behavior?

### ISSUE THREAD

**Issue by roblav96** [dmvaldman/samsara#29]
I'm trying to see if there's an option to disable this completely in v2.0?

I'm still using 0.1.3 because scrolling does not work on any of my pages when updating to v2.0

**Comment by dmvaldman** [comment]
Have you tried setting `{enableScroll : true}` on the `Context`, `ContainerSurface` or `Surface` that receives the touch. For `Contexts` this will let the page scroll, and for `Surfaces` it will let the inner content of a `Surface` be scrollable.

**Comment by roblav96** [comment]
I have not tried that.
```
context.mount( document.body, {
	enableScroll: true
} )
```

Like so?

**Comment by roblav96** [comment]
Yup that did it! Yay!

**Comment by dmvaldman** [comment]
:-) Glad that helped

Scrolling is a huge pain to get working in all use-cases (mostly because on mobile you want to suppress the entire window dragging). Sorry you have to jump through these hoops with an awkward API, but I haven't figured out a better way.

**Comment by roblav96** [comment]
No problem at all!!! I'm loving the design of everything so far.

My only complaint is that the render engine does not completely stop on idle. It just keeps firing RAF even when I close my app (cordova) and eats up minor memory. I'm hoping apple won't reject me for it.

**Comment by dmvaldman** [comment]
That's strange that it would run even with the app closed... The canceling of the RAF will definitely be coming in a future version. It's the next priority after adding and removing elements (which is on the removal branch currently)

**Comment by dmvaldman** [comment]
@roblav96 If you do publish an app to the app store, I'd like to see it, even a test version. Happy to tweet about it as well.

**Comment by roblav96** [comment]
Yes that would be awesome! I've dumped about 9 months into this project and used famous v3, then famous engine, and finally samsara and its by far the best. I'll certainly let you know when it's out. Should be next week.
