### ISSUE TITLE
PID Controller?

### ISSUE THREAD

**Issue by culyun** [dmvaldman/samsara#30]
I've been playing (read hacking) the Carousel demo.  Sometimes the page transitions end up partly "off page".  Have you thought about using a PI controller to eliminate the steady state error?

**Comment by dmvaldman** [comment]
That's an interesting idea, but in reality there is no "uncertainty" in the system. If you find yourself off page, this is more likely a bug that I'd rather fix directly than massage with a system on top of it. Do you find yourself off page when the screen is resized (or rotated on mobile)? This is a known bug in the `Scrollview`, or does the bug appear regardless?
