### ISSUE TITLE
Transitionable.on('end'   fires twice

### ISSUE THREAD

**Issue by dcsan** [dmvaldman/samsara#31]
I see a couple of events fire for when an animation ends.

```
  surface.on('click', function() {
      size.set([0.5, 0.5], {duration: 500}, resetAnim);
  });

  size.on('end', function() {
    // size.set([boxWidth,  boxHeight], {duration: 2000});
    clog('size.end');
  });
```

**Comment by dcsan** [comment]
![image](https://cloud.githubusercontent.com/assets/514002/13246836/dae33df0-d9ca-11e5-981b-7ce690f05743.png)

**Comment by dcsan** [comment]
this makes it hard to trigger the start of another anim when one completes (although i can use the callback, the events are just a bit nicer syntax)

**Comment by dmvaldman** [comment]
I'll need a little more information to be able to reproduce this. Is `size` a `Transitionable`, is it the `surfaces` `.size` property? What happens in `resetAnim`?
