### ISSUE TITLE
Parallax drag support

### ISSUE THREAD

**Issue by ghost** [dmvaldman/samsara#38]
@dmvaldman Hi David, just thought I'd give a heads up for the parallax scroll demo (with the cats): it would be nice if it had drag ability for the scrolling.

I'm in Linux, and the touchpad behaves like a scroll wheel, where the scroll jumps instead of being smooth (Due to the fact that Chrome Linux uses GTK2). Others will also won't see the effect if they have older mice with scroll wheels.

The new homepage looks awesome! :smiley:

**Comment by trusktr-goin** [comment]
Oops, I meant to post as @trusktr. x}

**Comment by dmvaldman** [comment]
Oh, so you can scroll with a mouse drag? That's a good point

**Comment by trusktr** [comment]
:+1:

**Comment by dmvaldman** [comment]
Added in 1f79b09. The ParallaxCats demo demonstrates this here 

https://github.com/dmvaldman/samsara/blob/master/examples/ParallaxCats/js/app/ParallaxCats.js#L16
