### ISSUE TITLE
Reason for no "Mixed Mode" (and physics)

### ISSUE THREAD

**Issue by eallik** [dmvaldman/samsara#4]
What is the reason, if any aside from lack of resources/time, for not attempting to implement something comparable to Famous' Mixed Mode? Will there be any alternatives for building 3D and WebGL apps using Samsara?

Also how about a physics engine?  Should it simply be possible to use a 3rd party one in combination with Samsara?

**Comment by dmvaldman** [comment]
Currently, WebGL support is not being investigated. This project began from v0.3 of Famous which had no support for "mixed mode." Perhaps down the road it can be added, but the focus for now is DOM. If you're a WebGL person, feel free to experiment! I imagine one would create a new kind of `Surface` and `Context` (which would be a canvas tag with a WebGL context) where the CSS3 transform would position things in the context. Other nodes, in addition to `SizeNode` and `LayoutNode`, can be added that correspond to GL properties, such as light sources, etc.

I'm currently working on a small physics engine, and that's a very important missing feature. I created the physics engine for Famous, so I have experience here. The main thing I never got to building, was just how physics and other transitions, like tweens, could interoperate. Other physics engines can be added, though it's best if they make no opinions on rendering and instead just export numbers. You could then take these numbers and map them to `transforms` or `opacity` etc. Stay tuned, though, I'll have physics up in a week or so.

**Comment by steveblue** [comment]
IMHO Mixed mode is a waste of time. Probably < 0.001 % of projects on the web actually require it.

**Comment by eallik** [comment]
Not a place for a debate, but I don't think any percentage of current and past projects requiring something that has been unheard of by 99.9999% of web devs, UX designers, interaction designers, data visualization experts, 2D/3D gaming, cross platform mobile apps, etc etc, is indicative of that something being "a waste of time" @steveblue

**Comment by steveblue** [comment]
Don't get me wrong @eallik, I am a huge proponent of WebGL, but the problem of Mixed mode is not necessarily a priority for development teams. How many web apps really need WebGL? The problem that needs to be solved IMHO is providing a way to display graphics accelerated Views that gives web apps close to near native performance. This should be one the main goals of a project like this one, not figuring out how to mix WebGL and DOM.

**Comment by dmvaldman** [comment]
Personally, there are some impressive examples of webGL and DOM cohabiting, such as http://aaron-meyers.com/

However, this is not the direction I have in mind for this project.
