### ISSUE TITLE
Howto dynamically add Surfaces?

### ISSUE THREAD

**Issue by daKmoR** [dmvaldman/samsara#45]
I feel a little dump but I though that would be way easy... 
However as far as it seem I can't make it work

```
surface.on('click', function(){
  var surface2 = new Surface({});
  context.add(surface2);  
});
```
I though something like this would work :p
am I approaching this the wrong way?

See example:
http://codepen.io/daKmoR/pen/GZygpd?editors=0010

**Comment by dmvaldman** [comment]
This should be fixed on the current master branch. I should probably cut a new release :-/

**Comment by daKmoR** [comment]
that would be pretty nice :) I like using the release version via npm :)
any timetable on that?

**Comment by dmvaldman** [comment]
v0.2.1 is released. Sorry for the wait!
