### ISSUE TITLE
Can I use Samsara in Meteor project?

### ISSUE THREAD

**Issue by ozergul** [dmvaldman/samsara#47]
Hi,
I wanna use Samsara in my Meteor project. Is it possible?

**Comment by dmvaldman** [comment]
I imagine you're thinking more along the lines of rendering templates from a meteor point of view. I'm sure this is doable, but haven't tried. You'll need to just call `setContent` on your Samsara surfaces when their data changes.

**Comment by ozergul** [comment]
If I drag samsara files to my project folder, there is a error. I think I can't use it in meteor. Thanks for reply David.

**Comment by dmvaldman** [comment]
If you can use jQuery, then you can use Samsara. There's nothing special about it. Maybe you should drag in the CommonJS version you can find in the `dist` directory instead of the AMD files in the `Samsara` directory.

**Comment by trusktr** [comment]
Meteor support ES6 modules now. Just `import Samsara from 'samsarajs'` after you've installed it from NPM.

Then use it as described in the Samsara docs.You'll have to get familiar with `Tracker.autorun` if you want to make things reactive imperatively (using JavaScript, no HTML).

If you want to render Blaze templates in Samsara Surfaces, you can do that: just look at the [Blaze.render](http://blazejs.org/api/blaze.html#Blaze-render) or [Blaze.renderWithData](http://blazejs.org/api/blaze.html#Blaze-renderWithData) methods, where the `parentNode` argument will be a Samsara Surace's element that you want to render into.

**Comment by trusktr** [comment]
@ozergul ^

**Comment by dmvaldman** [comment]
thanks @trusktr!

**Comment by trusktr** [comment]
@dmvaldman anytime! :}
