### ISSUE TITLE
Not responsive to split view on iOS

### ISSUE THREAD

**Issue by jd-carroll** [dmvaldman/samsara#50]
On iOS (iPad Pro's) it is possible for the view-port size to change when the user opens a split view application.  Currently the `Engine` doesn't propagate / respond to these changes in the view-port size.

**Comment by dmvaldman** [comment]
Interesting. Is a resize event fired in this case? If it turns out to be yes, it must mean that the window's size is unchanged. There's a check for this to prevent unnecessary resize events when the mobile safari/chrome Search bar appears when scrolling (which is super annoying).

**Comment by jd-carroll** [comment]
There is indeed a `resize` event; however when using split-view only the window `width` will change.  So I feel that it would still be possible to differentiate the two situations:
1. Safari/Chrome search bar -> only height changes -> ignore
2. Safari split-view -> only width changes -> propagate event
3. Safari/Chrome/et al. orientation -> both height and width change -> propagate event

We could take it even a step further and and look at the delta of the change.  If delta <= 8% ignore otherwise propagate an event.  (Note: 8% is a made up number)

**Comment by dmvaldman** [comment]
I think your idea of differentiating height and width changes will work. This whole thing is hacky, but I don't see any other way. I'll implement a fix soon.

**Comment by dmvaldman** [comment]
Would be great if you can confirm that 49d876c fixes the problem
