### ISSUE TITLE
[Question] will-change size

### ISSUE THREAD

**Issue by jd-carroll** [dmvaldman/samsara#56]
Currently when an dom-object is promoted, the css `will-change` property will only look for `transform` and `opacity`.  Is it worth while investigating ways to maintain an active "promotion" list?  Where the list could contain the values: `transform`, `opacity`, and `size`...

This would allow `commitSize` to participate in the performance gains associated with `will-change`.  (As opposed to the [current](https://github.com/dmvaldman/samsara/blob/master/samsara/dom/_DOMOutput.js#L235) where only [commitLayout](https://github.com/dmvaldman/samsara/blob/master/samsara/dom/Surface.js#L103L117) will participate)

I haven't tried this, so I'm unsure what (if any) performance gains would be achieved.

**Comment by dmvaldman** [comment]
`size` is not something that can be hardware accelerated. Only `transform` and `opacity` can be (as well as some others that are more rare, like `perspective`). The `will-change` property won't do anything for non-accelerated properties

**Comment by jd-carroll** [comment]
fair enough
