### ISSUE TITLE
Documentation on Transitions.Easing is out of date

### ISSUE THREAD

**Issue by diederikveelo** [dmvaldman/samsara#6]
The [documentation](http://samsarajs.org/docs/classes/Transitions.Easing.html) describes many easing transition but only 6 have actually been implemented.

current available easing transitions:
```
linear
easeIn
easeOut
easeInOut
easeOutBounce
spring
```

**Comment by dmvaldman** [comment]
Ah, this may be confusing and not well documented, but the easing curves you mentioned are there by default. To get the ones in `transitions/Easing.js` (which has 20-odd more) you'll need to require them in and then register them.

```
var Easing = require('samsara/transitions/Easing');
var TweenTransition = require('samsara/transitions/TweenTransition');
var Transitionable = require('samsara/core/Transitionable');

TweenTransition.register('inQuad', Easing.inQuad);

var t = new Transitionable(0);
t.set(100, {curve : 'inQuad', duration : 500});
```

This API will likely change soon, and I'll just include all the Easing curves by default.

**Comment by diederikveelo** [comment]
Ah, that makes sense, sorry I didn't see that.
