### ISSUE TITLE
React Native

### ISSUE THREAD

**Issue by zyonnetworks** [dmvaldman/samsara#61]
Can/Should SamsajaJS be integrated with "React Native"?

**Comment by dmvaldman** [comment]
I don't know enough of how React Native works to address this question. If it's possible in a way that fits with the architecture of Samsara then I am happy to pursue it and offer guidance to others interested in pursuing it.

**Comment by zyonnetworks** [comment]
Here is some sample React Native code:

```
'use strict';

import React, { Component } from 'react'
import { StyleSheet, Image, View, Text } from 'react-native';

var styles = StyleSheet.create({
  container: {
    marginTop: 65
  }
});

class PropertyView extends Component {

  render() {
    var property = this.props.property;
    var stats = property.bedroom_number + ' bed ' + property.property_type;
    if (property.bathroom_number) {
      stats += ', ' + property.bathroom_number + ' ' + (property.bathroom_number > 1
        ? 'bathrooms' : 'bathroom');
    }

    var price = property.price_formatted.split(' ')[0];

    return (
      <View style={styles.container}>
        <Image style={styles.image source={{uri: property.img_url}} />
        <View style={styles.heading}>
          <Text style={styles.price}>{price}</Text>
          <Text style={styles.title}>{property.title}</Text>
          <View style={styles.separator}/>
        </View>
        <Text style={styles.description}>{stats}</Text>
        <Text style={styles.description}>{property.summary}</Text>
      </View>
    );
  }
}

module.exports = PropertyView;

```
React Native seems to handle the layout and provides the bridge to close to native mobile performance.  It would be cool to use SamsaraJS to handle the animations / physics... I know SamsaraJS updates the DOM (shadow dom), so I don't know how that would factor in.

Based on the code above, do you think SamsaraJS could be integrated?

**Comment by dmvaldman** [comment]
You can think of Samsara as a way of outputting CSS3 transforms, opacity and size. That's all it does and all it will ever do. Currently Samsara sends these into the DOM. However the way I see Samsara "integrating" with another library, like React Native, is that it sends these values somewhere else. This is the handoff step. So in theory, React Native creates the components, and Samsara injects into them a position, size, etc on the screen. I haven't built out these integration libraries, but don't see any reason why they wouldn't work in principle.
