### ISSUE TITLE
Question : Can Samsara leverage the capabilities of shadow-dom ??

### ISSUE THREAD

**Issue by ameykshirsagar** [dmvaldman/samsara#65]
Hi,
I just want to know if any version of samsarajs will be able to work in Shadow DOM by creating native nodes of DOM, using createShadowRoot (or by using Polymer JS) for a widget(s) and create "sub-nodes" using Samsara.Surface in those native nodes, with their own render tree. 
Will it be an overhead on resources and rendering??
Just asking. 

Thank you

**Comment by dmvaldman** [comment]
All Samsara does is export 3d transforms and opacities into DOM elements. They can be shadow elements, or regular DOM elements.
