### ISSUE TITLE
Awesome work

### ISSUE THREAD

**Issue by mrjjwright** [dmvaldman/samsara#73]
I have never seen a lib like this on the web, with the amount of detailed work on coordinating mouse, gestures, scrolling and animation.   This type of work is, as you point out, typically only seen in iOS and was copied by Android.   I actually have never seen a project like this on native either.  The coordination done on native is under the hood and not exposed as a continuous elegant API.   View controller animations on IOS, e.g. are not interruptible and continuous.    It would be interesting to port this to native with a simple JS bridge (simpler than the one for React Native hopefully) and see how it works with already solid UIScrollViews and just transforming UIViews.

It also seems that part of what you have discovered is the power of making a continuous stream transforms a core rendering primitive for modern UI development.   Using only 3 layout primitives, sizing, transforms and opacity seems to eliminate large classes of layout and animation inconsistencies although there is a lot of work needed to rebuild the expressive layout of flex and grid layouts which you have already done.

You have moved on at least temporarily to other work but have been trying to grok the direction you were playing with before you left.  It looks like the noqueue branch isn't that far off of master and the ideas you were playing with there are pretty non impacting to the overall API.   I am hopeful that the core ideas here will live on.   Getting the scroll view and scrolling layouts and animations right and reliable seems to me to be a key to making this work long term.

Also, it's so freeing to get away from React style diffing and highly nested UIs which have dominated my mind for the last few years.   I had recently run into the limitations in reasoning about rendering with that approach and had gone searching for compelling alternatives the day I found Samsara.  On a hike I had wondered aloud in my brain if there would be some way to get rid of almost all UI hierarchy and this lib proved the power of doing so.

A bit of a ramble but want you to know how important and well received this work has been for me.  It has really given me hope.

**Comment by dmvaldman** [comment]
Wow. Thanks! Messages like these definitely make me want to commit more time to the project. You seem to grok many of the core ideals, and I'm always looking for strong contributors. 

The changes I was trying to experiment with the `noqueue` branch and others were to get the "stream" style programming working better with batching and dependencies. For example a `MergedStream` should only fire an event once even if several streams feeding into it are firing simultaneously, so there must be some sort of batching, which means you have to wait for some time before acting. Then if one `MergedStream` subscribes from another, the waiting logic becomes a little more complicated. Also I was struggling with subscribing and unsubscribing streams while they were active and having all the logic be consistent. With my time off from the project, I certainly have been getting more ideas on how to handle these cases elegantly. That said I'm always interested in discussing architectural decisions with others.

**Comment by mrjjwright** [comment]
I really feel like this is very important work and I hope you can figure this out.  I have some kind of high level thoughts.

1) A stable core API of this project is the basic `Node`/`Surface`/`Context` api with the layout primitives of `transform`, `opacity`, `size`, `align` and `origin`.  These are excellent primitives.
2) Representing values that change over time is done via the `Transitionable` api.  This API reminds me a lot of the `Animated` api on React Native and is a proven flexible and powerful for a wide variety of animation needs.  It's one of my favorite parts of React Native and I am glad it's here.
3) This project has a very strong notion of computed input values that are kept in sync with animation.  No other major UI library provides a consistent stable abstraction of gestures, mouse inputs and other inputs that directly factor into layout and animation.    The only other libraries that I know of that provide a super strong notion of computed values are Vue.js and Mobx (Moon.js is another recent excellent example).
4) The flat rendering product of this library is super unique.

So I am totally rambling and repeating myself again but the core message here is: please don't stop.  :)
