### ISSUE TITLE
Is Samsara viable when implementing animations designed in Framer?

### ISSUE THREAD

**Issue by newswim** [dmvaldman/samsara#75]
I recently started using Framer and was wondering if anyone had considered trying to map objects and events to Samsara, or how something like that might happen. There's a [Framer JS library](https://github.com/koenbok/Framer) which I haven't dug into that much.. but seems to handle a certain amount of interpolation (requires WebKit).

Just curious, sorry there are no code examples in this issue 😬

**Comment by dmvaldman** [comment]
That would be quite a neat (and sophisticated) integration indeed! I don't think anyone is working on it unfortunately. I really like what the folks at Framer have done. I'm not so familiar with the internals of Framer and how an integration would work, though I imagine it would be quite involved as Framer and Samsara are very opinionated on a lot of the same things. Maybe @koenbok would like to chime in.
